version: '3.2'
services:
  web:
    container_name: school-board-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "6080:80"
    volumes:
    - .:/var/www/html

  db:
    container_name: school-board-mysql
    image: mysql:5.7.29
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --character-set-server=utf8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: school_board
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devpass
    ports:
    - 6033:3306

  adminer:
    container_name: school-board-dbadmin
    image: adminer
    restart: always
    ports:
    - 8080:8080